#!/bin/bash

function getWallpaper() {
  [[ -n "$1" ]] && echo "$1" && return
  [[ -f "$WALLPAPER_IMAGE_FILE" ]] && echo "$WALLPAPER_IMAGE_FILE" && return
}

function setNotificationsPaused() {
  command -v dunstctl 2>/dev/null || return
  dunstctl set-paused "$1"
}

function lockScreen() {
  local wallpaper="$1"

  local blue_light='#5fd7ff'
  local blue_medium='#00afd7'
  local blue_dark='#005f87'
  local green_light='#d7ff5f'
  local red_light='#ff005f'
  local red_dark='#af0000'

  i3lock \
    --nofork \
    --image "$wallpaper" \
    --tiling \
    --ignore-empty-password \
    --indicator \
    --clock \
    --keylayout=0 \
    --layoutcolor=${blue_medium}ff \
    --timestr="%H:%M" \
    --timecolor=${blue_light}ff \
    --datestr="%A, %d.%m.%Y" \
    --datecolor=${blue_light}ff \
    --radius=110 \
    --ring-width=9 \
    --line-uses-ring \
    --ringcolor="${blue_dark}ff" \
    --insidecolor=${blue_dark}22 \
    --separatorcolor=${blue_light}ff \
    --keyhlcolor=${blue_light}ff \
    --bshlcolor=${red_dark}ff \
    --veriftext="Correct...?" \
    --verifcolor=${green_light}ff \
    --insidevercolor=${green_light}22 \
    --ringvercolor=${green_light}ff \
    --wrongtext="Nope!" \
    --noinputtext="Empty" \
    --insidewrongcolor=${red_light}22 \
    --ringwrongcolor=${red_dark}ff \
    --wrongcolor=${red_light}ff >>/tmp/testi.log 2>&1
}

setNotificationsPaused true
lockScreen "$(getWallpaper "$1")"
setNotificationsPaused false
