#!/bin/bash

function getWallpaper() {
  [[ -n "$1" ]] && echo "$1" && return
  [[ -f "$WALLPAPER_IMAGE_FILE" ]] && echo "$WALLPAPER_IMAGE_FILE" && return
}

function setNotificationsPaused() {
  command -v dunstctl 2>/dev/null || return
  dunstctl set-paused "$1"
}

function lockScreen() {
  local wallpaper="$1"

  local blue_light='#5fd7ff'
  local blue_medium='#00afd7'
  local blue_dark='#005f87'
  local green_light='#d7ff5f'
  local red_light='#ff005f'
  local red_dark='#af0000'

  i3lock \
    --nofork \
    --image "$wallpaper" \
    --tiling \
    --ignore-empty-password \
    --indicator \
    --clock \
    --color=${blue_medium}ff \
    --time-str="%H:%M" \
    --time-color=${blue_light}ff \
    --date-str="%A, %d.%m.%Y" \
    --date-color=${blue_light}ff \
    --keylayout=1 \
    --layout-color=${blue_light}ff \
    --radius=110 \
    --ring-width=9 \
    --line-uses-ring \
    --ring-color="${blue_dark}ff" \
    --inside-color=${blue_dark}22 \
    --separator-color=${blue_light}ff \
    --keyhl-color=${blue_light}ff \
    --bshl-color=${red_dark}ff \
    --verif-text="Correct...?" \
    --verif-color=${green_light}ff \
    --insidever-color=${green_light}22 \
    --ringver-color=${green_light}ff \
    --wrong-text="Nope!" \
    --noinput-text="Empty" \
    --insidewrong-color=${red_light}22 \
    --ringwrong-color=${red_dark}ff \
    --wrong-color=${red_light}ff
}

setNotificationsPaused true
lockScreen "$(getWallpaper "$1")"
setNotificationsPaused false
